apiVersion: v1
kind: Service
metadata:
  name: django-messaging-production
spec:
  selector:
    app: django-messaging
    version: blue  # Initially points to blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
# To switch to green, update selector to version: green
# kubectl patch service django-messaging-production -p '{"spec":{"selector":{"version":"green"}}}'